services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE:-nextcloud}:${NEXTCLOUD_TAG:-apache}
    container_name: ${SERVICE_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITEHOST=${NEXTCLOUD_OVERWRITEHOST}
      - OVERWRITEPROTOCOL=${NEXTCLOUD_OVERWRITEPROTOCOL}
      - OVERWRITECLIURL=${NEXTCLOUD_OVERWRITECLIURL}
      - NEXTCLOUD_INIT_HTACCESS=true
    depends_on:
      nextcloud-redis:
        condition: service_healthy
      nextcloud-database:
        condition: service_healthy
    expose:
      - "${SERVICE_PORT}"
    volumes:
      - ./data/html:/var/www/html
    labels:
      - pangolin.public-resources.${BLUEPRINT_NAME}.name=${RESOURCE_NAME}
      - pangolin.public-resources.${BLUEPRINT_NAME}.full-domain=${SERVICE_SUBDOMAIN}.${BASE_DOMAIN}
      - pangolin.public-resources.${BLUEPRINT_NAME}.protocol=http
      - pangolin.public-resources.${BLUEPRINT_NAME}.targets[0].method=http
    networks:
      - pangolin
      - nextcloud

  nextcloud-redis:
    image: ${REDIS_IMAGE:-redis}:${REDIS_TAG:-7-alpine}
    container_name: nextcloud-redis
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud

  nextcloud-database:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_TAG:-17-alpine}
    container_name: nextcloud-database
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud

networks:
  pangolin:
    external: true
    name: ${PANGOLIN_DOCKER_NETWORK:-pangolin_default}
  nextcloud:
    driver: bridge
